epochs: 10
data_path: '/home/user/Downloads/dataset/0P'
img_save_freq: 1000
critic_iter_per_gen: 5
batch_size: 32
lr: 0.00005
beta1: 0.5
beta2: 0.999
lambda_p: 100
lambda_gaze: 5
lambda_recon: 50
image_save_freq: 1000
model_save_freq: 2
use_comet: 'offline' #'online' or 'offline' or None
comet_workspace: 'generative-models'
comet_project: 'gaze-estimation'
