epochs: 300
data_path: '/home/user/Downloads/dataset/0P'
critic_iter_per_gen: 5
batch_size: 32
test_batch_size: 21
lr: 0.00005
beta1: 0.5
beta2: 0.999
lambda_p: 100
lambda_gaze: 5
lambda_recon: 50
image_save_freq: 10
model_save_freq: 50
resume_training: False
debug_path: 'debug'
use_comet: 'online' #'online' or 'offline' or None
comet_workspace: 'generative-models'
comet_project: 'gaze-estimation'
